#define RESETS_BASE (0x40020000)
#define RESETS_RESET_RW (*(volatile unsigned long *)(RESETS_BASE + 0x0 + 0x0000))
#define RESETS_RESET_XOR (*(volatile unsigned long *)(RESETS_BASE + 0x0 + 0x1000))
#define RESETS_RESET_SET (*(volatile unsigned long *)(RESETS_BASE + 0x0 + 0x2000))
#define RESETS_RESET_CLR (*(volatile unsigned long *)(RESETS_BASE + 0x0 + 0x3000))
#define RESETS_RESET_DONE_RW (*(volatile unsigned long *)(RESETS_BASE + 0x8 + 0x0000))
#define RESETS_RESET_DONE_XOR (*(volatile unsigned long *)(RESETS_BASE + 0x8 + 0x1000))
#define RESETS_RESET_DONE_SET (*(volatile unsigned long *)(RESETS_BASE + 0x8 + 0x2000))
#define RESETS_RESET_DONE_CLR (*(volatile unsigned long *)(RESETS_BASE + 0x8 + 0x3000))

#define SIO_BASE (0xd0000000)
#define SIO_GPIO_OUT_RW (*(volatile unsigned long *)(SIO_BASE + 0x10))
#define SIO_GPIO_OUT_SET (*(volatile unsigned long *)(SIO_BASE + 0x18))
#define SIO_GPIO_OUT_CLR (*(volatile unsigned long *)(SIO_BASE + 0x20))
#define SIO_GPIO_OUT_XOR (*(volatile unsigned long *)(SIO_BASE + 0x28))
#define SIO_GPIO_OE_RW (*(volatile unsigned long *)(SIO_BASE + 0x30))
#define SIO_GPIO_OE_SET (*(volatile unsigned long *)(SIO_BASE + 0x38))
#define SIO_GPIO_OE_CLR (*(volatile unsigned long *)(SIO_BASE + 0x40))
#define SIO_GPIO_OE_XOR (*(volatile unsigned long *)(SIO_BASE + 0x48))

#define IO_BANK0_BASE (0x40028000)
#define IO_BANK0_GPIO10_STATUSL_RW (*(volatile unsigned long *)(IO_BANK0_BASE + 0x050 + 0x0000))
#define IO_BANK0_GPIO10_STATUSL_XOR (*(volatile unsigned long *)(IO_BANK0_BASE + 0x050 + 0x1000))
#define IO_BANK0_GPIO10_STATUSL_SET (*(volatile unsigned long *)(IO_BANK0_BASE + 0x050 + 0x2000))
#define IO_BANK0_GPIO10_STATUSL_CLR (*(volatile unsigned long *)(IO_BANK0_BASE + 0x050 + 0x3000))
#define IO_BANK0_GPIO10_CTRL_RW (*(volatile unsigned long *)(IO_BANK0_BASE + 0x054 + 0x0000))
#define IO_BANK0_GPIO10_CTRL_XOR (*(volatile unsigned long *)(IO_BANK0_BASE + 0x054 + 0x1000))
#define IO_BANK0_GPIO10_CTRL_SET (*(volatile unsigned long *)(IO_BANK0_BASE + 0x054 + 0x2000))
#define IO_BANK0_GPIO10_CTRL_CLR (*(volatile unsigned long *)(IO_BANK0_BASE + 0x054 + 0x3000))
#define IO_BANK0_GPIO25_STATUSL_RW (*(volatile unsigned long *)(IO_BANK0_BASE + 0x0C8 + 0x0000))
#define IO_BANK0_GPIO25_STATUSL_XOR (*(volatile unsigned long *)(IO_BANK0_BASE + 0x0C8 + 0x1000))
#define IO_BANK0_GPIO25_STATUSL_SET (*(volatile unsigned long *)(IO_BANK0_BASE + 0x0C8 + 0x2000))
#define IO_BANK0_GPIO25_STATUSL_CLR (*(volatile unsigned long *)(IO_BANK0_BASE + 0x0C8 + 0x3000))
#define IO_BANK0_GPIO25_CTRL_RW (*(volatile unsigned long *)(IO_BANK0_BASE + 0x0CC + 0x0000))
#define IO_BANK0_GPIO25_CTRL_XOR (*(volatile unsigned long *)(IO_BANK0_BASE + 0x0CC + 0x1000))
#define IO_BANK0_GPIO25_CTRL_SET (*(volatile unsigned long *)(IO_BANK0_BASE + 0x0CC + 0x2000))
#define IO_BANK0_GPIO25_CTRL_CLR (*(volatile unsigned long *)(IO_BANK0_BASE + 0x0CC + 0x3000))

#define PADS_BANK0_BASE (0x40038000)
#define PADS_BANK0_BASE_GPIO10_RW (*(volatile unsigned long *)(PADS_BANK0_BASE + 0x2C + 0x0000))
#define PADS_BANK0_BASE_GPIO10_XOR (*(volatile unsigned long *)(PADS_BANK0_BASE + 0x2C + 0x1000))
#define PADS_BANK0_BASE_GPIO10_SET (*(volatile unsigned long *)(PADS_BANK0_BASE + 0x2C + 0x2000))
#define PADS_BANK0_BASE_GPIO10_CLR (*(volatile unsigned long *)(PADS_BANK0_BASE + 0x2C + 0x3000))
#define PADS_BANK0_BASE_GPIO25_RW (*(volatile unsigned long *)(PADS_BANK0_BASE + 0x68 + 0x0000))
#define PADS_BANK0_BASE_GPIO25_XOR (*(volatile unsigned long *)(PADS_BANK0_BASE + 0x68 + 0x1000))
#define PADS_BANK0_BASE_GPIO25_SET (*(volatile unsigned long *)(PADS_BANK0_BASE + 0x68 + 0x2000))
#define PADS_BANK0_BASE_GPIO25_CLR (*(volatile unsigned long *)(PADS_BANK0_BASE + 0x68 + 0x3000))

#define CLOCKS_BASE (0x40010000)
#define CLK_REF_CTRL_RW (*(volatile unsigned long *)(CLOCKS_BASE + 0x30 + 0x0000))
#define CLK_REF_CTRL_XOR (*(volatile unsigned long *)(CLOCKS_BASE + 0x30 + 0x1000))
#define CLK_REF_CTRL_SET (*(volatile unsigned long *)(CLOCKS_BASE + 0x30 + 0x2000))
#define CLK_REF_CTRL_CLR (*(volatile unsigned long *)(CLOCKS_BASE + 0x30 + 0x3000))
#define CLK_SYS_CTRL_RW (*(volatile unsigned long *)(CLOCKS_BASE + 0x3C + 0x0000))
#define CLK_SYS_CTRL_XOR (*(volatile unsigned long *)(CLOCKS_BASE + 0x3C + 0x1000))
#define CLK_SYS_CTRL_SET (*(volatile unsigned long *)(CLOCKS_BASE + 0x3C + 0x2000))
#define CLK_SYS_CTRL_CLR (*(volatile unsigned long *)(CLOCKS_BASE + 0x3C + 0x3000))
#define CLK_SYS_RESUS_CTRL_RW (*(volatile unsigned long *)(CLOCKS_BASE + 0x84 + 0x0000))
#define CLK_SYS_RESUS_CTRL_XOR (*(volatile unsigned long *)(CLOCKS_BASE + 0x84 + 0x1000))
#define CLK_SYS_RESUS_CTRL_SET (*(volatile unsigned long *)(CLOCKS_BASE + 0x84 + 0x2000))
#define CLK_SYS_RESUS_CTRL_CLR (*(volatile unsigned long *)(CLOCKS_BASE + 0x84 + 0x3000))

#define XOSC_BASE (0x40048000)
#define XOSC_CTRL_RW (*(volatile unsigned long *)(XOSC_BASE + 0x00 + 0x0000))
#define XOSC_CTRL_XOR (*(volatile unsigned long *)(XOSC_BASE + 0x00 + 0x1000))
#define XOSC_CTRL_SET (*(volatile unsigned long *)(XOSC_BASE + 0x00 + 0x2000))
#define XOSC_CTRL_CLR (*(volatile unsigned long *)(XOSC_BASE + 0x00 + 0x3000))
#define XOSC_STATUS_RW (*(volatile unsigned long *)(XOSC_BASE + 0x04 + 0x0000))
#define XOSC_STATUS_XOR (*(volatile unsigned long *)(XOSC_BASE + 0x04 + 0x1000))
#define XOSC_STATUS_SET (*(volatile unsigned long *)(XOSC_BASE + 0x04 + 0x2000))
#define XOSC_STATUS_CLR (*(volatile unsigned long *)(XOSC_BASE + 0x04 + 0x3000))
#define XOSC_STARTUP_RW (*(volatile unsigned long *)(XOSC_BASE + 0x0C + 0x0000))
#define XOSC_STARTUP_XOR (*(volatile unsigned long *)(XOSC_BASE + 0x0C + 0x1000))
#define XOSC_STARTUP_SET (*(volatile unsigned long *)(XOSC_BASE + 0x0C + 0x2000))
#define XOSC_STARTUP_CLR (*(volatile unsigned long *)(XOSC_BASE + 0x0C + 0x3000))
#define XOSC_COUNT_RW (*(volatile unsigned long *)(XOSC_BASE + 0x10 + 0x0000))
#define XOSC_COUNT_XOR (*(volatile unsigned long *)(XOSC_BASE + 0x10 + 0x1000))
#define XOSC_COUNT_SET (*(volatile unsigned long *)(XOSC_BASE + 0x10 + 0x2000))
#define XOSC_COUNT_CLR (*(volatile unsigned long *)(XOSC_BASE + 0x10 + 0x3000))

#define TIMER0_BASE (0x400b0000)
#define TIMER0_TIMEHW (*(volatile unsigned long *)(TIMER0_BASE + 0x00))
#define TIMER0_TIMELW (*(volatile unsigned long *)(TIMER0_BASE + 0x04))
#define TIMER0_TIMEHR (*(volatile unsigned long *)(TIMER0_BASE + 0x08))
#define TIMER0_TIMELR (*(volatile unsigned long *)(TIMER0_BASE + 0x0C))
#define TIMER0_ALARM0 (*(volatile unsigned long *)(TIMER0_BASE + 0x10))
#define TIMER0_ALARM1 (*(volatile unsigned long *)(TIMER0_BASE + 0x14))
#define TIMER0_ALARM2 (*(volatile unsigned long *)(TIMER0_BASE + 0x18))
#define TIMER0_ALARM3 (*(volatile unsigned long *)(TIMER0_BASE + 0x1C))
#define TIMER0_ARMED (*(volatile unsigned long *)(TIMER0_BASE + 0x20))
#define TIMER0_TIMERAWH (*(volatile unsigned long *)(TIMER0_BASE + 0x24))
#define TIMER0_TIMERAWL (*(volatile unsigned long *)(TIMER0_BASE + 0x28))
#define TIMER0_DBGPAUSE (*(volatile unsigned long *)(TIMER0_BASE + 0x2C))
#define TIMER0_PAUSE (*(volatile unsigned long *)(TIMER0_BASE + 0x30))
#define TIMER0_LOCKED (*(volatile unsigned long *)(TIMER0_BASE + 0x34))
#define TIMER0_SOURCE (*(volatile unsigned long *)(TIMER0_BASE + 0x38))
#define TIMER0_INTR (*(volatile unsigned long *)(TIMER0_BASE + 0x3C))
#define TIMER0_INTE (*(volatile unsigned long *)(TIMER0_BASE + 0x40))
#define TIMER0_INTF (*(volatile unsigned long *)(TIMER0_BASE + 0x44))
#define TIMER0_INTS (*(volatile unsigned long *)(TIMER0_BASE + 0x48))

#define TIMER1_BASE (0x400b8000)
#define TIMER1_TIMEHW (*(volatile unsigned long *)(TIMER1_BASE + 0x00))
#define TIMER1_TIMELW (*(volatile unsigned long *)(TIMER1_BASE + 0x04))
#define TIMER1_TIMEHR (*(volatile unsigned long *)(TIMER1_BASE + 0x08))
#define TIMER1_TIMELR (*(volatile unsigned long *)(TIMER1_BASE + 0x0C))
#define TIMER1_ALARM0 (*(volatile unsigned long *)(TIMER1_BASE + 0x10))
#define TIMER1_ALARM1 (*(volatile unsigned long *)(TIMER1_BASE + 0x14))
#define TIMER1_ALARM2 (*(volatile unsigned long *)(TIMER1_BASE + 0x18))
#define TIMER1_ALARM3 (*(volatile unsigned long *)(TIMER1_BASE + 0x1C))
#define TIMER1_ARMED (*(volatile unsigned long *)(TIMER1_BASE + 0x20))
#define TIMER1_TIMERAWH (*(volatile unsigned long *)(TIMER1_BASE + 0x24))
#define TIMER1_TIMERAWL (*(volatile unsigned long *)(TIMER1_BASE + 0x28))
#define TIMER1_DBGPAUSE (*(volatile unsigned long *)(TIMER1_BASE + 0x2C))
#define TIMER1_PAUSE (*(volatile unsigned long *)(TIMER1_BASE + 0x30))
#define TIMER1_LOCKED (*(volatile unsigned long *)(TIMER1_BASE + 0x34))
#define TIMER1_SOURCE (*(volatile unsigned long *)(TIMER1_BASE + 0x38))
#define TIMER1_INTR (*(volatile unsigned long *)(TIMER1_BASE + 0x3C))
#define TIMER1_INTE (*(volatile unsigned long *)(TIMER1_BASE + 0x40))
#define TIMER1_INTF (*(volatile unsigned long *)(TIMER1_BASE + 0x44))
#define TIMER1_INTS (*(volatile unsigned long *)(TIMER1_BASE + 0x48))
